FROM node:12 AS builder

ARG REACT_APP_AUTH0_DOMAIN
ARG REACT_APP_AUTH0_CLIENT_ID
ARG REACT_APP_AUTH0_ISSUER
ARG REACT_APP_AUTH0_AUDIENCE
ARG REACT_APP_DOMAIN_ROOT
ARG REACT_APP_DOMAIN_API

ENV REACT_APP_AUTH0_DOMAIN "$REACT_APP_AUTH0_DOMAIN"
ENV REACT_APP_AUTH0_CLIENT_ID "$REACT_APP_AUTH0_CLIENT_ID"
ENV REACT_APP_AUTH0_ISSUER "$REACT_APP_AUTH0_ISSUER"
ENV REACT_APP_AUTH0_AUDIENCE "$REACT_APP_AUTH0_AUDIENCE"
ENV REACT_APP_DOMAIN_ROOT "$REACT_APP_DOMAIN_ROOT"
ENV REACT_APP_DOMAIN_API "$REACT_APP_DOMAIN_API"

WORKDIR /app

COPY ./package.json ./
RUN yarn global add serve

RUN yarn install
COPY . .

RUN yarn build

EXPOSE 5000
CMD ["serve", "-s", "build"]
